# Site settings
title: Personal Webpage of Max Horn
description: >
    I work as a Applied Scientist for AWS AI where I explore the intersection of Machine Learning,
    Deep Learning and Causality. In particular, I am interested building models that understand
    notions of objects present in the real world.<br />

    Prior to my position at AWS I was a PhD Student in Machine Learning and Computational Biology
    at ETH Zürich and worked on the development of <b>deep learning methods for real world
    medical time series</b>, <b>Dimensionality Reduction</b> and <b>Topological Machine Learning</b>.<br />

    My interests include but are not limited to: <b>Machine Learning for
    Healthcare</b>, <b>Probabilistic Modelling</b>, <b>Time Series Modelling</b> and
    <b>Interpretable Machine Learning</b>.<br />

    Here I write about stuff I care about in the realm of science, programming,
    technology and crypto.  All opinions expressed are solely my own and do not
    express the views or opinions of my employer.
url: 'https://ExpectationMax.github.io'
baseurl: ''
google_analytics: 'UA-167128850-1'
disqus_shortname: 'ExpectationMax'

author:
  name: 'Max Horn'
  email: maexlich@gmail.com
  twitter_username: ExpectationMax
  cv_path: assets/Max_Horn-CV.pdf
#  facebook_username: joshgerdes
  github_username:  ExpectationMax
  linkedin_username:  max-horn-ml

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'
        comments: true

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'vendor']
