# Site settings
title: Personal Webpage of Max Horn
description: >
    I'm a PhD Student in Machine Learning and Computational Biology and work on
    the development of deep learning methods for real world medical time series.
    My interests include but are not limited to: Machine Learning for Healthcare,
    Probabilistic Modelling, Time Series Modelling and Interpretable Machine Learning.

    Here I write about stuff I care about in the realm of science, programming and technology.
url: 'https://ExpectationMax.github.io'
baseurl: ''
google_analytics: 'UA-167128850-1'
disqus_shortname: 'ExpectationMax'

author:
  name: 'Max Horn'
  email: maexlich@gmail.com
  twitter_username: ExpectationMax
  cv_path: assets/Max_Horn-CV.pdf
#  facebook_username: joshgerdes
  github_username:  ExpectationMax
  linkedin_username:  max-horn-ml

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'
        comments: true

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'vendor']
