# Site settings
title: Webpage of Max Horn
description: 
    This is the Webpage of Max Horn, PhD Student in Machine Learning and Computational Biology at ETH Zürich.
url: 'https://ExpectationMax.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'ExpectationMax'

author:
  name: 'Max Horn'
  email: maexlich@gmail.com
  twitter_username: ExpectationMax
  cv_path: assets/Max_Horn-CV.pdf
#  facebook_username: joshgerdes
  github_username:  ExpectationMax
#  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'
        comments: true

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'vendor']
